apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kus
  janus-idp.io/tekton: kus
  backstage.io/kubernetes-id: kus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kus
resources:
- deployment.yaml
- route.yaml
- service.yaml
